mysort: mysort.o quick_sort.o selection_sort.o insertion_sort.o bubble_sort.o merge_sort.o
	gcc -g -Wall mysort.o quick_sort.o selection_sort.o  insertion_sort.o bubble_sort.o merge_sort.o	-o mysort
mysort.o: mysort.c
	gcc -c -g -Wall mysort.c
quick_sort.o: quick_sort.c
	gcc -c -g -Wall quick_sort.c
selection_sort.o: selection_sort.c
	gcc -c -g -Wall  selection_sort.c
insertion_sort.o: insertion_sort.c
	gcc -c -g -Wall insertion_sort.c
bubble_sort.o: bubble_sort.c
	gcc -c -g -Wall bubble_sort.c
merge_sort.o: merge_sort.c
	gcc -c -g -Wall merge_sort.c
